# Generated by Django 3.1.5 on 2021-02-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_points',
            field=models.IntegerField(default=0),
        ),
    ]
